import { Geist, Geist_Mono, Poppins, Inter, Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
	weight: "400",
	subsets: ["latin"],
});
const poppins = Poppins({
	weight: "400",
	subsets: ["latin"],
});
const inter = Inter({
	weight: "400",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${roboto.className} ${inter.className} ${roboto.poppins} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
